name: Playwright CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r playwright_AWH_py/requirement.txt
        pip install behave
        python -m playwright install chromium

    - name: Recreate state.json
      shell: powershell
      run: |
        $data = "${{ secrets.STATE_JSON }}"
        python -c "import base64,gzip; open('state.json','wb').write(gzip.decompress(base64.b64decode('$data')))"

    - name: Run Tests
      shell: powershell
      run: |
        $env:PYTHONPATH = "$PWD/playwright_AWH_py"
        $env:PYTHONIOENCODING = "utf-8"
        python -X utf8 -m behave playwright_AWH_py/features

    - name: Upload Screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: failure-screenshots
        path: screenshots/
        if-no-files-found: ignore